packages:
  - apps/*
  - packages/*

catalog:
  tailwindcss: 4.1.18
  '@tailwindcss/postcss': 4.1.18
  '@tailwindcss/vite': 4.1.18
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  postcss: 8.5.6
  react: 19.2.4
  react-dom: 19.2.4


onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
