packages:
  - apps/*
  - packages/*

catalog:
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  react: 19.2.4
  react-dom: 19.2.4

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
