/* eslint-disable import/order */
import type { Metadata } from 'next';
import '@/app/globals.css';
import '@krakstack/ui/styles-ui.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">{children}</body>
    </html>
  );
}
