name: Vercel Deploy '@krakstack/utils' Docs production

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_UTILS_DOCS }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_UTILS_DOCS }}

on:
  workflow_dispatch:
    
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOY_ACCESS_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_DEPLOY_ACCESS_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_DEPLOY_ACCESS_TOKEN }}

